### ISSUE TITLE
Draco lib can't be installed

### ISSUE THREAD

**Issue by Nek** [polygonjs/polygonjs#56] opened 2023-03-07 02:11 UTC
I have a local installation of polygonjs.
`Windows > Libraries > Install Draco` ends up with `threejs is not installed` error message.

**Comment by frading** [comment] 2023-03-07 10:04
Sorry about that, this is a bug should be fixed in 1.4.2-1, so assuming you are on an earlier version, could you upgrade and try again?

I've just tried it on my end and it works fine on linux, but if you still see the problem, it would debug this if you can share the `.polygonjs-editor.log` file

**Comment by Nek** [comment] 2023-03-08 12:38
@frading you absolutely shouldn't be sorry. Great project that came out of nowhere and seems like a silver bullet for the things I want to build. The pricing is also extremely competitive. I'll put effort to integrate the tool into my workflow.

I'm also attaching `package.json` for more context. My project was created as react-three-fiber-ts template.
https://gist.github.com/Nek/4742a56fd2f3b579f7d05c5d4e7bff90

**Comment by frading** [comment] 2023-03-08 14:21
> Great project that came out of nowhere and seems like a silver bullet for the things I want to build. The pricing is also extremely competitive. I'll put effort to integrate the tool into my workflow.

Great to hear!

And I can reproduce the issue, thanks a lot for the log and mentioning which template you used. It looks like the react-three-fiber plugin and and polygonjs-editor depend on different versions of polygonjs, so the folder where the gltf/draco files end up is not `node_modules/three/examples/jsm/libs/draco/` as expected, but instead `node_modules/polygonjs-editor/node_modules/three/examples/jsm/libs/draco/`.

That of course shouldn't happen, I'll have a think how I can fix that in next release.

In the mean time, since `Windows->Libraries->Install Draco` simply copies the draco files into the folder `public/three/js/libs/draco/`, you can do the same manually with this command: 

``` bash
mkdir -p public/three/js/libs/draco && cp -rf node_modules/polygonjs-editor/node_modules/three/examples/jsm/libs/draco/* public/three/js/libs/draco/
```
And then just press the reload button of the fileGLTF node, or reload the editor page (no need to restart the local server).

**Comment by frading** [comment] 2023-03-11 19:32
I've release version 1.4.3-4 of the [cli tool](https://github.com/polygonjs/create-polygonjs), which fixes the react three fiber version. So if you create a project from scratch, installing the gltf/draco library will work just fine.
If you want to update your project, you need to upgrade the following packages:

- @polygonjs/react-three-fiber to ^1.4.2
- @react-three/fiber to ^8.11.10
- polygonjs-editor to ^1.4.2-1

Or you can simply copy the [full package.json from the cli repo](https://github.com/polygonjs/create-polygonjs/blob/main/templates/react-three-fiber-ts/package.json) 

Closing the issue now, but you're welcome to reopen if needed

**Closed by frading** 2023-03-11 19:32 UTC

**Comment by Nek** [comment] 2023-03-13 03:52
Thanks a lot! It works.
Another thing worth mentioning, one of the mistakes that's easy to make for beginners, is forgetting to run *both* server `npm run dev` and polygon editor `npm run polygon`. Maybe the template should include a command that does both so it's bulletproof for newcomers.

**Comment by frading** [comment] 2023-03-13 11:02
Great, thank you for confirming.

And regarding forgetting one command, yes, I was actually wondering about that, so it's good that you bring it up.
In addition to forgetting one, I've seen beginners, not yet familiar with shells and commands, who didn't know they should open a 2nd shell for the 2nd command.

That said, if I was to add a 4th line to the presented next steps, which would then look like `npm run dev & npm run polygon`, it may appear to be a 4th command to run. I would also like to encourage people to run those 2 commands separately, so that their outputs don't get mixed up. Or if one crashes, it's clear which one has.

And then some may be fine not running `npm run dev`, as they would use only the export from the editor, using File->Export.

So I'll have a think, there may be a simple tweak in formatting/color on  what's currently there. Or maybe I'll end up with what you suggest.
